### ISSUE TITLE
Adding eval support for algorithms other than Genetic Programming

### ISSUE THREAD

**Issue by ancorso** [sisl/ExprOptimization.jl#17]
I noticed that Grammatical Evolution, Cross-Entropy, or PIPE don't currently support grammars that have eval statements "_()". Is this a fundamental limitation of those algorithms or just an implementation challenge?

I have a project where I would like to compare the performance of these different algorithms to Genetic Programming but I need the eval syntax to sample continuous values. I would be happy to look into implementing this feature if I can get a little direction.

**Comment by rcnlee** [comment]
These are limitations of the algorithms, unfortunately.  In GP, individuals are trees, so you can call eval when the individual is created and store the generated value with the tree node.  However, the other algorithms use other representations for individuals which would be difficult to support a persistent concrete value.  In GE, the intermediate representation is an integer array, but you can't associate it with any particular element of the array because if any of the previous elements change, the meaning of the element changes also, which can render your value meaningless.  In CE, the distribution of the population gets fitted down to weights in the grammar, which would also be a difficult mapping.

**Comment by ancorso** [comment]
That makes sense! Thanks for taking the time to explain!
